//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_LeThiThuyHang_5701_WebsitebanhangcafeRuNam
{


    public partial class Dangky
    {
    }
}
